### ISSUE TITLE
Chests have wrong item textures

### ISSUE THREAD

**Issue by 22858** [Potion-Studios/All-The-Wood-Weve-Got#1]
there is something wrong with these chests
![图片](https://github.com/user-attachments/assets/76b3ff37-69d0-4b87-8052-4a9b1b0582bc)
but it looks all right when placed down🤔
![图片](https://github.com/user-attachments/assets/5c22239f-0ade-4ddd-9ab4-4b70bbd8143a)

it's 1.20.1 forge

**Comment by 22858** [comment]
[latest.log](https://github.com/user-attachments/files/17727134/latest.log)

I don't know what is the mod conflicting with. Would you mind going through my log?

**Comment by JT122406** [comment]
If I were to guess could you try this profile in single player without everycomp and see if it still happens

**Comment by 22858** [comment]
I tried this profile without everycomp and it still happens.

I tried in another profile with everycomp. It was all right.
![图片](https://github.com/user-attachments/assets/b08ed1d9-c025-419d-aed1-0583c5aabe2f)

**Comment by 22858** [comment]
It's the problem with Enhanced Block Entities. (I'm using connector)
Sorry to bother you😭
