### ISSUE TITLE
[Question] About the crafting tables and bookshelves

### ISSUE THREAD

**Issue by An-thracene** [Potion-Studios/All-The-Wood-Weve-Got#5]
Why not adjust the crafting table and bookshelf variants from BWG to this mod?

**Comment by JT122406** [comment]
Well it would make sense, since they are already in BWG removing them would be a problem for a lot of users as the ids would change and stuff like that

**Comment by An-thracene** [comment]
Then could there be a configuration to disable those variants in BWG? Since this mod is an official extension I think I don't need to open another issue in BWG's github page in this case

**Comment by JT122406** [comment]
Possibly could do something like a data fixer and a feature flag and then move them but I will have to talk to the dev team and decide if this is something we want to do

**Comment by JT122406** [comment]
Owner Decided he wants to keep those in normal BWG as they fit with what we want where these blocks don't

**Comment by DarthCaesium** [comment]
How can I disable the recipes of these crafting table variants using datapacks then? I personally don't want crafting table variants to be in my modpack, so I need a way to disable the recipes to obtain them.
